### ISSUE TITLE
Integrated wordpay   using cocoapods but  stuck  at this error

### ISSUE THREAD

**Issue by DeshaboinaRaki** [Worldpay/worldpay-lib-ios#5]
Integrated  worldpay into my project using cocoapods  but  getting this error 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AFHTTPRequestOperation", referenced from:
      objc-class-ref in libWorldpay.a(Worldpay.o)
      objc-class-ref in libWorldpay.a(ThreeDSController.o)
      objc-class-ref in libWorldpay.a(APMController.o)
  "_OBJC_CLASS_$_AFHTTPRequestOperationManager", referenced from:
      objc-class-ref in libWorldpay.a(WorldpayUtils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

how to   solve this cant find any solution, help me out  from this issue

**Comment by dcapilla** [comment]
Hello @DeshaboinaRaki,

It seems that you haven't installed AFNetworking library as part of your iOS project. Please follow the step by step guide on our github readme page (step number 5 of the "Integration" section) in order to install AFNetworking. After you've installed it the error should disappear.

Thanks

**Comment by DeshaboinaRaki** [comment]
Thanks dcapilla   for your suggestion   solved the issue
