### ISSUE TITLE
Without cocapods can I use the worldpay 

### ISSUE THREAD

**Issue by smilydronavalli** [Worldpay/worldpay-lib-ios#6]
Hi,

Please help me how to use worldpay SDK with out cocoapods.

Thanks 
Smily

**Comment by dcapilla** [comment]
Hello Smily,

Since the Worldpay SDK makes use of the [AFNetworking](https://github.com/AFNetworking/AFNetworking) library, we strongly recommend to use cocoapods in order to install it (it's also easier). However, if you want to proceed with manual installation, you would need to get rid of the /Pods folder, and also get rid of the "Check Pods Manifest" phase under the "Build Phases" of the project settings and then install AFNetworking manually. In order to install a library manually, you would normally do:
1. \- Download the library from GitHub: https://github.com/AFNetworking/AFNetworking
2. \- Add the files to Xcode
3. \- Import headers

However, the ability to do this depends on the library itself (in this case AFNetworking). So you would need to check their documentation in order to verify how to import the library manually.

I hope it helps.

David

**Comment by smilydronavalli** [comment]
Hello David,

Thank you .
