### ISSUE TITLE
Can I display address1,address2,zip in mobile sdk payment

### ISSUE THREAD

**Issue by smilydronavalli** [Worldpay/worldpay-lib-ios#7]
Hi,

I need to display all the fileds like address1,address2,city and passcode in  standard viewController.

Thanks
Smily

**Comment by dcapilla** [comment]
Hello Smily,

I am not sure if I understand the question. You can have a look to our sample app, which is under the TestWorldpayLibrary folder, that makes use of the library and displays the fields you request in order to create an order:

![simulator screen shot 14 jun 2016 16 57 51](https://cloud.githubusercontent.com/assets/946605/16049852/365a9bb8-3251-11e6-93b4-4318bd347ca9.png)

Best regards,

David
